server:
  port: 8080
  
spring:
  application:
      name: allspark    
  datasource:
    url: jdbc:mysql://13.209.75.24:3306/ALL_SPARK_DB
    username: root
    password: root
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update


     